In [2]:
import pandas as pd
import numpy as np
import math as math
from sklearn.model_selection import KFold
from sklearn import svm
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix

In [3]:
data = pd.read_csv('MNIST_HW4.csv')
labels = data.iloc[:,0]

In [4]:
X = data.iloc[0:-1, :]
y = labels
#setting up k-fold cv

kf = KFold(n_splits = 5)
kf.get_n_splits(data)

5

In [5]:
linear_svc = SVC(kernel='linear')
rbf_svc = SVC(kernel='rbf')
poly_svc = SVC(kernel='poly')
counter = 1


for train_index, test_index in kf.split(X):
    
    train_X = X.iloc[train_index]
    test_X = X.iloc[test_index]
    train_y = y.iloc[train_index]
    test_y = y.iloc[test_index]
    #print("TRAIN:", data.iloc[train_index], "TEST:", data.iloc[test_index])
    #print("TRAIN:", train_index, "TEST:", test_index)
    #linear_svc.fit(X.iloc[train_index], y.iloc[train_index])
    #print(linear_svc.fit(X.iloc[train_index], y.iloc[train_index]))
    
    print("===============", counter, "===============")
    
    #for linear
    linear_svc.fit(train_X, train_y)
    pred_y = linear_svc.predict(test_X)
    print("LINEAR:")
    print(confusion_matrix(test_y, pred_y))
    print("Accuracy", linear_svc.score(test_X, test_y))
    print("")
    winner = "linear"
    w = linear_svc.score(test_X, test_y)
    
    #for rbf
    rbf_svc.fit(train_X, train_y)
    pred_y = rbf_svc.predict(test_X)
    print("RBF:")
    #print(confusion_matrix(test_y, pred_y))
    print("Accuracy", rbf_svc.score(test_X, test_y))
    print("")
    if (rbf_svc.score(test_X, test_y) > w):
        w = rbf_svc.score(test_X, test_y)
        winner = "rbf"
    
    #for poly
    poly_svc.fit(train_X, train_y)
    pred_y = poly_svc.predict(test_X)
    print("POLY:")
    #print(confusion_matrix(test_y, pred_y))
    print("Accuracy", poly_svc.score(test_X, test_y))
    print("")
    if (poly_svc.score(test_X, test_y) > w):
        w = poly_svc.score(test_X, test_y)
        winner = "poly"
        
#     print("And the winner is...")
#     print(winner, "!")
#     print("with an accuracy of: ", w)
#     print("")
    
    counter = counter + 1
    
    
    #rbf_svc.fit(trainX)

# for train, test in kf.split(X):
#     print("%s %s" % (train, test))

=============== 1 ===============
LINEAR:
[[23  0  0  0  0  1  0  0  0  0]
 [ 0 16  1  0  0  0  0  0  0  0]
 [ 0  0 21  0  0  1  0  1  0  0]
 [ 0  0  1 15  0  1  0  2  1  0]
 [ 0  0  0  0 20  0  0  0  0  4]
 [ 0  0  0  2  0 19  1  0  0  0]
 [ 1  0  0  0  0  0 22  0  1  0]
 [ 0  0  0  0  1  0  0 11  0  1]
 [ 0  1  0  0  0  1  0  0 11  1]
 [ 0  0  0  0  1  0  0  1  0 17]]
Accuracy 0.875

RBF:
Accuracy 0.895

POLY:
Accuracy 0.86

=============== 2 ===============
LINEAR:
[[19  0  0  0  0  0  1  0  0  0]
 [ 0 20  0  0  0  0  0  0  0  0]
 [ 1  0 17  0  0  0  0  0  0  0]
 [ 0  0  0 13  0  1  0  0  0  0]
 [ 0  1  0  0 24  0  0  0  0  1]
 [ 0  0  0  0  1 15  0  0  1  0]
 [ 0  0  2  0  0  0 19  0  0  0]
 [ 0  1  1  1  1  0  0 19  0  1]
 [ 0  0  0  1  0  1  0  0 13  0]
 [ 0  0  0  0  2  0  0  4  0 19]]
Accuracy 0.89

RBF:
Accuracy 0.92

POLY:
Accuracy 0.845

=============== 3 ===============
LINEAR:
[[19  0  0  0  1  0  0  0  0  0]
 [ 0 16  0  0  0  0  0  0  0  0]
 [ 0  0 16  3  0  0  1  0  1  0